[tool.poetry]
name = "nlp-syntag"
version = "0.1.0"
description = ""
authors = ["max <max906993@gmail.com>"]
readme = "README.md"
package-mode = true
packages = [{include = "nlp_syntag", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
