"""empty message

Revision ID: 0dab22c99b3e
Revises: c21b55e18a91
Create Date: 2024-06-14 00:11:53.839157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dab22c99b3e'
down_revision: Union[str, None] = 'c21b55e18a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('ingestion_pipeline_id', sa.Text(), nullable=False))
    op.add_column('embeddings', sa.Column('search_pipeline_id', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'embeddings', ['id'])
    op.drop_column('embeddings', 'username')
    op.drop_column('embeddings', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('embeddings', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'embeddings', type_='unique')
    op.drop_column('embeddings', 'search_pipeline_id')
    op.drop_column('embeddings', 'ingestion_pipeline_id')
    # ### end Alembic commands ###
