"""chunk table

Revision ID: c3eb1fde5238
Revises: 40142688d5ed
Create Date: 2024-08-17 17:09:51.630836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3eb1fde5238"
down_revision: Union[str, None] = "40142688d5ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('\"chunk_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(precision=3),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("knowledgeUuid", sa.UUID(), nullable=False),
        sa.Column("split_type", sa.Text(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["knowledgeUuid"],
            ["knowledge.uuid"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunks")
    # ### end Alembic commands ###
