"""empty message

Revision ID: 1945ef09e237
Revises: 1b5535499e67
Create Date: 2024-09-12 18:13:21.932651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1945ef09e237"
down_revision: Union[str, None] = "1b5535499e67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("account_balance_payment_method", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "account_balance_payment_method")
    # ### end Alembic commands ###
