"""empty message

Revision ID: fb8d96c56dd2
Revises: b253eddecc10
Create Date: 2024-05-06 22:23:49.120316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb8d96c56dd2"
down_revision: Union[str, None] = "b253eddecc10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_assistant",
        sa.Column("model", sa.Enum("GPT_3_5", "GPT_4", name="LLM"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_assistant", "model")
    # ### end Alembic commands ###
