"""change to cascading on delete for convo and message

Revision ID: 9f622551b874
Revises: 689a9496d67c
Create Date: 2024-07-11 02:04:57.090892

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9f622551b874"
down_revision: Union[str, None] = "689a9496d67c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("conversation_userUuid_fkey", "conversation", type_="foreignkey")
    op.create_foreign_key(
        None,
        "conversation",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("message_conversationUuid_fkey", "message", type_="foreignkey")
    op.drop_constraint("message_userUuid_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        None,
        "message",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "message",
        "conversation",
        ["conversationUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_userUuid_fkey",
        "message",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "message_conversationUuid_fkey",
        "message",
        "conversation",
        ["conversationUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.create_foreign_key(
        "conversation_userUuid_fkey",
        "conversation",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
