"""empty message

Revision ID: 461d37c1c431
Revises: c5706d3e52d3
Create Date: 2024-03-24 17:51:06.248873

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "461d37c1c431"
down_revision: Union[str, None] = "c5706d3e52d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "faqbot_message_faqbotConversationUuid_fkey",
        "faqbot_message",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "faqbot_message",
        "faqbot_conversation",
        ["faqbotConversationUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "faqbot_message", type_="foreignkey")
    op.create_foreign_key(
        "faqbot_message_faqbotConversationUuid_fkey",
        "faqbot_message",
        "conversation",
        ["faqbotConversationUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
