"""use files_assistants as junction table

Revision ID: 87e8db634345
Revises: 5415cbfe3696
Create Date: 2024-07-25 23:47:02.861522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87e8db634345"
down_revision: Union[str, None] = "5415cbfe3696"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assistant_files_voice_assistants")
    op.drop_table("files_assistants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_files_voice_assistants",
        sa.Column(
            "assistant_files_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "voice_assistant_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assistant_files_id"],
            ["assistant_files.id"],
            name="assistant_files_voice_assistants_assistant_files_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["voice_assistant_id"],
            ["voice_assistant.id"],
            name="assistant_files_voice_assistants_voice_assistant_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "assistant_files_id",
            "voice_assistant_id",
            name="assistant_files_voice_assistants_pkey",
        ),
    )
    # ### end Alembic commands ###
