"""caller and assistant pn, starred viewed

Revision ID: f9ef642c9f6c
Revises: bc7aae4ac834
Create Date: 2024-07-23 15:03:20.909915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9ef642c9f6c"
down_revision: Union[str, None] = "bc7aae4ac834"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("assistant_pn", sa.Text(), nullable=True))
    op.add_column("conversation", sa.Column("caller_pn", sa.Text(), nullable=True))
    op.add_column(
        "conversation",
        sa.Column("starred", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "conversation",
        sa.Column("viewed", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_column("conversation", "pn")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation", sa.Column("pn", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("conversation", "viewed")
    op.drop_column("conversation", "starred")
    op.drop_column("conversation", "caller_pn")
    op.drop_column("conversation", "assistant_pn")
    # ### end Alembic commands ###
