"""add files_assistants table

Revision ID: 5415cbfe3696
Revises: 11e94c76742e
Create Date: 2024-07-25 22:57:52.208558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# from sqlalchemy.orm import Session
# from app.database.tables.assistant_files import AssistantFiles
# from app.database.tables.files_assistants import FilesAssistants
# from app.database.tables.voice_assistant import VoiceAssistant

# revision identifiers, used by Alembic.
revision: str = "5415cbfe3696"
down_revision: Union[str, None] = "11e94c76742e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_assistants",
        sa.Column("assistant_files_uuid", sa.UUID(), nullable=False),
        sa.Column("voice_assistant_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_files_uuid"],
            ["assistant_files.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_assistant_uuid"],
            ["voice_assistant.uuid"],
        ),
        sa.PrimaryKeyConstraint("assistant_files_uuid", "voice_assistant_uuid"),
    )
    # # ### end Alembic commands ###
    # bind = op.get_bind()
    # session = Session(bind=bind)
    # links = session.execute(
    #     sa.text("SELECT * FROM assistant_files_voice_assistants")
    # ).fetchall()
    #
    # for link in links:
    #     voice_assistant = (
    #         session.query(VoiceAssistant)
    #         .filter(VoiceAssistant.id == link["voice_assistant_id"])
    #         .first()
    #     )
    #     file = (
    #         session.query(AssistantFiles)
    #         .filter(AssistantFiles.id == link["assistant_files_id"])
    #         .first()
    #     )
    #     new_row = FilesAssistants(
    #         assistant_files_uuid=file.uuid, voice_assistant_uuid=voice_assistant.uuid
    #     )
    #     session.add(new_row)
    # session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files_assistants")
    # ### end Alembic commands ###
