"""change enums

Revision ID: 508ecf79a5fc
Revises: a2ca55d5b896
Create Date: 2024-06-29 23:52:55.394214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "508ecf79a5fc"
down_revision: Union[str, None] = "a2ca55d5b896"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(sa.text("ALTER TYPE \"Role\" ADD VALUE 'ASSISTANT'"))
    op.execute(sa.text("ALTER TYPE \"Role\" ADD VALUE 'TOOL'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TYPE \"Role\" DROP VALUE 'ASSISTANT'"))
    op.execute(sa.text("ALTER TYPE \"Role\" DROP VALUE 'TOOL'"))
    # ### end Alembic commands ###
