"""empty message

Revision ID: b001319a2290
Revises: 223bdc42dc98
Create Date: 2024-10-18 14:06:54.178615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b001319a2290'
down_revision: Union[str, None] = '223bdc42dc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_call_transcription', sa.Column('appointment_booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_call_transcription', 'appointment_booked')
    # ### end Alembic commands ###
