"""empty message

Revision ID: 04b703919b8d
Revises: 08d5e3eeacd2
Create Date: 2024-07-19 22:41:24.154456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b703919b8d'
down_revision: Union[str, None] = '08d5e3eeacd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_files_voice_assistants',
    sa.Column('assistant_files_id', sa.Integer(), nullable=False),
    sa.Column('voice_assistant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_files_id'], ['assistant_files.id'], ),
    sa.ForeignKeyConstraint(['voice_assistant_id'], ['voice_assistant.id'], ),
    sa.PrimaryKeyConstraint('assistant_files_id', 'voice_assistant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant_files_voice_assistants')
    # ### end Alembic commands ###
