"""remove llm enum

Revision ID: 7500c8efaae6
Revises: 3e019be303a1
Create Date: 2024-07-28 14:05:32.298193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7500c8efaae6"
down_revision: Union[str, None] = "3e019be303a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "model")
    op.drop_column("faqbot_conversation", "model")
    op.drop_column("voice_assistant", "model")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_assistant",
        sa.Column(
            "model",
            postgresql.ENUM("GPT_3_5", "GPT_4", "GPT_4O_MINI", name="LLM"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "faqbot_conversation",
        sa.Column(
            "model",
            postgresql.ENUM("GPT_3_5", "GPT_4", "GPT_4O_MINI", name="LLM"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "model",
            postgresql.ENUM("GPT_3_5", "GPT_4", "GPT_4O_MINI", name="LLM"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
