"""empty message

Revision ID: 9ca6b8aa7c0e
Revises: 93e32438b721
Create Date: 2024-07-16 12:37:09.300081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca6b8aa7c0e'
down_revision: Union[str, None] = '93e32438b721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_files',
    sa.Column('id', sa.Integer(), server_default=sa.text('nextval(\'"user_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('gc_bucket_name', sa.Text(), nullable=False),
    sa.Column('gc_bucket_path', sa.Text(), nullable=False),
    sa.Column('openai_file_id', sa.Text(), nullable=False),
    sa.Column('openai_file_name', sa.Text(), nullable=False),
    sa.Column('userUuid', sa.UUID(), nullable=False),
    sa.Column('voiceAssistantUuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['userUuid'], ['user.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voiceAssistantUuid'], ['voice_assistant.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_assistant_files_uuid'), 'assistant_files', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_files_uuid'), table_name='assistant_files')
    op.drop_table('assistant_files')
    # ### end Alembic commands ###
