"""conversation_cache

Revision ID: 995b9cf3ab1f
Revises: a97a24ee456e
Create Date: 2024-08-22 22:37:27.348624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "995b9cf3ab1f"
down_revision: Union[str, None] = "a97a24ee456e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column(
            "cache",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "cache")
    # ### end Alembic commands ###
