"""add voice assistant and phone number tables

Revision ID: 76c7bdcc5ce5
Revises: 461d37c1c431
Create Date: 2024-04-13 18:35:43.627783

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76c7bdcc5ce5"
down_revision: Union[str, None] = "461d37c1c431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_assistant",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('\"voice_assistant_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("userUuid", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(precision=3),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("profile_pic_url", sa.Text(), nullable=True),
        sa.Column("chatgpt_assistant_id", sa.Text(), nullable=True),
        sa.Column("vapi_assistant_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userUuid"], ["user.uuid"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_assistant_uuid"), "voice_assistant", ["uuid"], unique=True
    )
    op.create_table(
        "phone_number",
        sa.Column(
            "id",
            sa.Integer(),
            server_default=sa.text("nextval('\"phone_number_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("userUuid", sa.UUID(), nullable=False),
        sa.Column("voice_assistant_uuid", sa.UUID(), nullable=True),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(precision=3),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("pn", sa.Text(), nullable=True),
        sa.Column("vapi_phone_number_id", sa.Text(), nullable=True),
        sa.Column("stripe_subscription_item_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userUuid"], ["user.uuid"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["voice_assistant_uuid"],
            ["voice_assistant.uuid"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_phone_number_uuid"), "phone_number", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phone_number_uuid"), table_name="phone_number")
    op.drop_table("phone_number")
    op.drop_index(op.f("ix_voice_assistant_uuid"), table_name="voice_assistant")
    op.drop_table("voice_assistant")
    # ### end Alembic commands ###
