"""empty message

Revision ID: fa8a39923ae9
Revises: b001319a2290
Create Date: 2024-10-18 14:15:04.166368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8a39923ae9'
down_revision: Union[str, None] = 'b001319a2290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_call_transcription', 'appointment_booked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_call_transcription', 'appointment_booked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
