"""file_display_name

Revision ID: 40142688d5ed
Revises: af4d1169ab04
Create Date: 2024-08-11 16:28:39.836985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40142688d5ed"
down_revision: Union[str, None] = "af4d1169ab04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge", sa.Column("file_display_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "file_display_name")
    # ### end Alembic commands ###
