"""empty message

Revision ID: 997f39dfc0ae
Revises: 8dbc115de6be
Create Date: 2024-10-17 22:08:50.952986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997f39dfc0ae'
down_revision: Union[str, None] = '8dbc115de6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_call_transcription', sa.Column('voicemail', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_call_transcription', 'voicemail')
    # ### end Alembic commands ###
