"""empty message

Revision ID: c5706d3e52d3
Revises: 520f0c826994
Create Date: 2024-03-24 10:56:17.530778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5706d3e52d3"
down_revision: Union[str, None] = "520f0c826994"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation",
        "model",
        existing_type=postgresql.ENUM("GPT_3_5", "GPT_4", name="LLM"),
        nullable=True,
    )
    op.add_column("user", sa.Column("stripe_customer_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "stripe_customer_id")
    op.alter_column(
        "conversation",
        "model",
        existing_type=postgresql.ENUM("GPT_3_5", "GPT_4", name="LLM"),
        nullable=False,
    )
    # ### end Alembic commands ###
