"""empty message

Revision ID: 871c7c34bbb5
Revises: 2604b490f7a7
Create Date: 2024-08-04 11:28:45.639230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871c7c34bbb5'
down_revision: Union[str, None] = '2604b490f7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('document_ingestion_pipeline_id', sa.Text(), nullable=False))
    op.add_column('embeddings', sa.Column('document_search_pipeline_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'document_search_pipeline_id')
    op.drop_column('embeddings', 'document_ingestion_pipeline_id')
    # ### end Alembic commands ###
