"""vapiCallId

Revision ID: fedde0103976
Revises: a7799e94e128
Create Date: 2024-06-29 12:12:50.573764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fedde0103976"
down_revision: Union[str, None] = "a7799e94e128"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation", sa.Column("vapiCallId", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "vapiCallId")
    # ### end Alembic commands ###
