"""properly generate assistants to files

Revision ID: 3e019be303a1
Revises: ac4ac7a9cd15
Create Date: 2024-07-26 01:05:02.893113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e019be303a1"
down_revision: Union[str, None] = "87e8db634345"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistants_to_files",
        sa.Column("assistant_files_uuid", sa.UUID(), nullable=False),
        sa.Column("voice_assistant_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_files_uuid"],
            ["assistant_files.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_assistant_uuid"],
            ["voice_assistant.uuid"],
        ),
        sa.PrimaryKeyConstraint("assistant_files_uuid", "voice_assistant_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assistants_to_files")
    # ### end Alembic commands ###
