"""relaitonship between conversation and assistant

Revision ID: 52277f2a0b9f
Revises: df68ccde5bc7
Create Date: 2024-08-22 21:05:19.872441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52277f2a0b9f"
down_revision: Union[str, None] = "df68ccde5bc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "conversation", sa.Column("voice_assistant_uuid", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "conversation",
        "voice_assistant",
        ["voice_assistant_uuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
