"""empty message

Revision ID: fd8fca988953
Revises: 1769d2cdca53
Create Date: 2024-09-06 01:41:57.041039

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fd8fca988953"
down_revision: Union[str, None] = "1769d2cdca53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_useruuid_url", "knowledge", ["userUuid", "url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_useruuid_url", "knowledge", type_="unique")
    # ### end Alembic commands ###
