"""DB stuff for vectors.

Revision ID: c21b55e18a91
Revises: fb8d96c56dd2
Create Date: 2024-06-13 21:58:25.161445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21b55e18a91'
down_revision: Union[str, None] = 'fb8d96c56dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), server_default=sa.text('nextval(\'"embeddings_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cluster_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_uuid'), 'embeddings', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_uuid'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
