"""track user onboarding

Revision ID: a23df480bde1
Revises: 26ce0bd48402
Create Date: 2024-08-26 19:28:25.870451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a23df480bde1"
down_revision: Union[str, None] = "26ce0bd48402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "has_completed_onboarding",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_completed_onboarding")
    # ### end Alembic commands ###
