"""empty message

Revision ID: b4981ab953fc
Revises: 995b9cf3ab1f
Create Date: 2024-08-22 23:25:01.538703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4981ab953fc"
down_revision: Union[str, None] = "995b9cf3ab1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column(
            "status",
            postgresql.ENUM(
                "TRYING_TO_FIND_ISSUE",
                "FOUND_UNRESOLVABLE_ISSUE_WAITING_FOR_FINAL_ISSUE_DIAGNOSIS",
                "FOUND_UNIDENTIFIABLE_ISSUE_WAITING_FOR_FINAL_ISSUE_DIAGNOSIS",
                "FOUND_RESOLVABLE_ISSUE_WAITING_FOR_FINAL_ISSUE_DIAGNOSIS",
                "FOUND_AUTORESOLVABLE_ISSUE_WAITING_FOR_FINAL_ISSUE_DIAGNOSIS",
                "COLLECTING_ISSUE_INFO",
                "AUTORESOLVED_ISSUE",
                "CONVERSATION_ENDED",
                name="ConversationStatus",
            ),
            server_default=sa.text("'TRYING_TO_FIND_ISSUE'::\"ConversationStatus\""),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
