"""empty message

Revision ID: a0af2620c3e1
Revises: fd8fca988953
Create Date: 2024-09-08 17:56:23.541792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0af2620c3e1"
down_revision: Union[str, None] = "fd8fca988953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "embedding_tokens",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "account_balance", sa.Float(), server_default=sa.text("0"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "account_balance")
    op.drop_column("user", "embedding_tokens")
    # ### end Alembic commands ###
