"""empty message

Revision ID: 9355100fd726
Revises: b73bdc2f6d7b
Create Date: 2024-09-15 04:24:35.515330

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9355100fd726"
down_revision: Union[str, None] = "b73bdc2f6d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_journal_entry_userUuid_fkey", "user_journal_entry", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_journal_entry",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_journal_entry", type_="foreignkey")
    op.create_foreign_key(
        "user_journal_entry_userUuid_fkey",
        "user_journal_entry",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
    )
    # ### end Alembic commands ###
