"""empty message

Revision ID: 1769d2cdca53
Revises: 7fc0b1a94a7c
Create Date: 2024-09-03 21:04:55.983926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1769d2cdca53"
down_revision: Union[str, None] = "7fc0b1a94a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("content_start_index", sa.Integer(), nullable=True)
    )
    op.add_column(
        "chunks", sa.Column("content_last_index", sa.Integer(), nullable=True)
    )
    op.drop_column("chunks", "content")
    op.add_column("knowledge", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "content")
    op.add_column(
        "chunks", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("chunks", "content_last_index")
    op.drop_column("chunks", "content_start_index")
    # ### end Alembic commands ###
