"""assistants to knowledge

Revision ID: 1b6cc0eb3848
Revises: bb94ee7a1983
Create Date: 2024-08-11 11:46:47.943183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b6cc0eb3848"
down_revision: Union[str, None] = "bb94ee7a1983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.drop_column("voice_assistant", "assistant_files")
    op.alter_column(
        "knowledge",
        "id",
        server_default=sa.text("nextval('knowledge_id_seq'::regclass)"),
    )

    op.create_table(
        "assistants_to_knowledge",
        sa.Column("knowledge_uuid", sa.UUID(), nullable=False),
        sa.Column("voice_assistant_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_uuid"],
            ["knowledge.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_assistant_uuid"],
            ["voice_assistant.uuid"],
        ),
        sa.PrimaryKeyConstraint("knowledge_uuid", "voice_assistant_uuid"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assistants_to_knowledge")
    # ### end Alembic commands ###
