"""empty message

Revision ID: 223bdc42dc98
Revises: 997f39dfc0ae
Create Date: 2024-10-18 13:56:31.172406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223bdc42dc98'
down_revision: Union[str, None] = '997f39dfc0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_call_transcription', sa.Column('recording_url', sa.String(), nullable=True))
    op.add_column('manual_call_transcription', sa.Column('call_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_call_transcription', 'call_duration_seconds')
    op.drop_column('manual_call_transcription', 'recording_url')
    # ### end Alembic commands ###
