"""empty message

Revision ID: 95a48e90c108
Revises: 871c7c34bbb5
Create Date: 2024-08-04 11:56:29.641306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a48e90c108'
down_revision: Union[str, None] = '871c7c34bbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('document_delete_pipeline_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'document_delete_pipeline_id')
    # ### end Alembic commands ###
