"""store vapi config

Revision ID: 08d5e3eeacd2
Revises: 82afa1ddea66
Create Date: 2024-07-19 16:28:56.353628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "08d5e3eeacd2"
down_revision: Union[str, None] = "82afa1ddea66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_assistant",
        sa.Column(
            "vapi_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_assistant", "vapi_config")
    # ### end Alembic commands ###
