"""Create prompt components column -- will be used like so:

{
 "WebSummary": "<webscraped summary>",
 "FormalityPrompt": "<formality level's prompt>",
 "ToneOfVoicePrompt": "<tone of voice's prompt>"
 "Humor": "<humor level's prompt>",
 "Knowledge": "<knowledge>",
 "Instructions": "Instructions"
}

Revision ID: 928d7b063a15
Revises: 0dab22c99b3e
Create Date: 2024-07-04 18:34:41.421969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "928d7b063a15"
down_revision: Union[str, None] = "0dab22c99b3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_assistant",
        sa.Column(
            "prompt_components",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_assistant", "prompt_components")
    # ### end Alembic commands ###
