"""empty message

Revision ID: 70325965b6f2
Revises: 04b703919b8d
Create Date: 2024-07-19 23:21:39.820533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70325965b6f2'
down_revision: Union[str, None] = '04b703919b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assistant_files_voiceAssistantUuid_fkey', 'assistant_files', type_='foreignkey')
    op.drop_column('assistant_files', 'voiceAssistantUuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_files', sa.Column('voiceAssistantUuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('assistant_files_voiceAssistantUuid_fkey', 'assistant_files', 'voice_assistant', ['voiceAssistantUuid'], ['uuid'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###
