"""add cluster name

Revision ID: bb94ee7a1983
Revises: eb408aa3b018
Create Date: 2024-08-10 23:00:03.238946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb94ee7a1983"
down_revision: Union[str, None] = "eb408aa3b018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "embeddings",
        sa.Column(
            "cluster_name",
            sa.Text(),
            nullable=False,
            server_default="customdonotusestring",
        ),
    )
    op.alter_column("embeddings", "cluster_name", server_default=None)
    op.create_unique_constraint(None, "knowledge", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledge", type_="unique")
    op.drop_column("embeddings", "cluster_name")
    # ### end Alembic commands ###
