"""empty message

Revision ID: 7fc0b1a94a7c
Revises: 117c7fc58ce0
Create Date: 2024-09-02 17:54:37.167853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fc0b1a94a7c"
down_revision: Union[str, None] = "117c7fc58ce0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("voice_assistant", sa.Column("voice_enum", sa.Text(), nullable=True))
    op.drop_column("voice_assistant", "profile_pic_url")
    op.drop_column("voice_assistant", "vector_store_id")
    op.drop_column("voice_assistant", "chatgpt_assistant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_assistant",
        sa.Column(
            "chatgpt_assistant_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "voice_assistant",
        sa.Column("vector_store_id", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "voice_assistant",
        sa.Column("profile_pic_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("voice_assistant", "voice_enum")
    # ### end Alembic commands ###
