"""store user's personal phone number

Revision ID: 689a9496d67c
Revises: 508ecf79a5fc
Create Date: 2024-07-03 01:04:20.147737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "689a9496d67c"
down_revision: Union[str, None] = "508ecf79a5fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("pn", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pn")
    # ### end Alembic commands ###
