"""empty message

Revision ID: 117c7fc58ce0
Revises: 2a26965c5bc8
Create Date: 2024-09-01 02:26:33.157719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "117c7fc58ce0"
down_revision: Union[str, None] = "2a26965c5bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column(
            "durationInSeconds",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "durationInSeconds")
    # ### end Alembic commands ###
