"""empty message

Revision ID: a97a24ee456e
Revises: f76917474403
Create Date: 2024-08-22 22:09:50.311773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a97a24ee456e"
down_revision: Union[str, None] = "f76917474403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "currentIssue")
    op.drop_column("conversation", "currentField")
    op.drop_column("conversation", "issues")
    op.drop_column("conversation", "fieldDescriptions")
    op.drop_column("conversation", "apiSpecification")
    op.drop_column("conversation", "collectedFields")
    op.drop_column("conversation", "findIssueCount")
    op.drop_column("conversation", "phoneNumberUuid")
    op.drop_column("conversation", "fieldsToCollect")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column(
            "fieldsToCollect",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column("phoneNumberUuid", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "findIssueCount",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "collectedFields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "apiSpecification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "fieldDescriptions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "currentField",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversation",
        sa.Column(
            "currentIssue",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
