"""empty message

Revision ID: b253eddecc10
Revises: dff7721fb3ed
Create Date: 2024-05-06 06:29:37.331423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b253eddecc10"
down_revision: Union[str, None] = "dff7721fb3ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("voice_assistant", sa.Column("name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_assistant", "name")
    # ### end Alembic commands ###
