"""add index column to messages

Revision ID: a7799e94e128
Revises: 928d7b063a15
Create Date: 2024-06-29 01:39:45.607345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7799e94e128"
down_revision: Union[str, None] = "928d7b063a15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("index", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "index")
    # ### end Alembic commands ###
