"""empty message

Revision ID: e0231109c1f3
Revises: fa8a39923ae9
Create Date: 2024-10-19 13:05:37.759587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0231109c1f3'
down_revision: Union[str, None] = 'fa8a39923ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_call_transcription', sa.Column('appointment_value_in_dollars', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_call_transcription', 'appointment_value_in_dollars')
    # ### end Alembic commands ###
