"""empty message

Revision ID: db2bfa7f57b1
Revises: 4d258db5b103
Create Date: 2024-10-16 19:31:08.748826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db2bfa7f57b1'
down_revision: Union[str, None] = '4d258db5b103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_call_transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('call_sid', sa.String(), nullable=True),
    sa.Column('recording_sid', sa.String(), nullable=True),
    sa.Column('transcription_sid', sa.String(), nullable=True),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('caller_phone_number', sa.String(), nullable=True),
    sa.Column('called_phone_number', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_call_transcription_call_sid'), 'manual_call_transcription', ['call_sid'], unique=False)
    op.create_index(op.f('ix_manual_call_transcription_id'), 'manual_call_transcription', ['id'], unique=False)
    op.create_index(op.f('ix_manual_call_transcription_uuid'), 'manual_call_transcription', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_call_transcription_uuid'), table_name='manual_call_transcription')
    op.drop_index(op.f('ix_manual_call_transcription_id'), table_name='manual_call_transcription')
    op.drop_index(op.f('ix_manual_call_transcription_call_sid'), table_name='manual_call_transcription')
    op.drop_table('manual_call_transcription')
    # ### end Alembic commands ###
