"""empty message

Revision ID: 9e4d2c0504bc
Revises: 52277f2a0b9f
Create Date: 2024-08-22 21:30:21.766231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e4d2c0504bc"
down_revision: Union[str, None] = "52277f2a0b9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE conversation SET voice_assistant_uuid = "assistantId"::uuid')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column("assistantId", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "conversation", type_="unique")
    # ### end Alembic commands ###
