"""empty message

Revision ID: fde2c5bedb5d
Revises: 40aebefc9302
Create Date: 2024-11-25 14:37:25.769651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fde2c5bedb5d'
down_revision: Union[str, None] = '40aebefc9302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('twilio_call_sid', sa.Text(), nullable=True))
    op.add_column('conversation', sa.Column('direction', sa.Text(), nullable=True))
    op.alter_column('conversation', 'language',
               existing_type=postgresql.ENUM('ENGLISH', 'SPANISH', name='Language'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'language',
               existing_type=postgresql.ENUM('ENGLISH', 'SPANISH', name='Language'),
               nullable=False)
    op.drop_column('conversation', 'direction')
    op.drop_column('conversation', 'twilio_call_sid')
    # ### end Alembic commands ###
