"""empty message

Revision ID: 2a26965c5bc8
Revises: 0d4eb90cdc08
Create Date: 2024-09-01 01:08:08.993524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a26965c5bc8"
down_revision: Union[str, None] = "0d4eb90cdc08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_assistant",
        sa.Column(
            "conversation_duration_sum",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_assistant", "conversation_duration_sum")
    # ### end Alembic commands ###
