"""server url changes

Revision ID: a2ca55d5b896
Revises: fedde0103976
Create Date: 2024-06-29 23:23:53.165647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2ca55d5b896"
down_revision: Union[str, None] = "fedde0103976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation", sa.Column("phoneNumberUuid", sa.UUID(), nullable=True)
    )
    op.add_column("conversation", sa.Column("pn", sa.Text(), nullable=True))
    op.alter_column(
        "conversation", "assistantId", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation", "assistantId", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("conversation", "pn")
    op.drop_column("conversation", "phoneNumberUuid")
    # ### end Alembic commands ###
