"""empty message

Revision ID: 7ee6a4867c4c
Revises: 95a48e90c108
Create Date: 2024-08-05 02:25:28.978149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ee6a4867c4c'
down_revision: Union[str, None] = '95a48e90c108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistants_to_files')
    op.drop_index('ix_assistant_files_uuid', table_name='assistant_files')
    op.drop_table('assistant_files')
    op.add_column('voice_assistant', sa.Column('assistant_files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_assistant', 'assistant_files')
    op.create_table('assistant_files',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assistant_files_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gc_bucket_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gc_bucket_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('openai_file_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('openai_file_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userUuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userUuid'], ['user.uuid'], name='assistant_files_userUuid_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='assistant_files_pkey'),
    sa.UniqueConstraint('id', name='assistant_files_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_assistant_files_uuid', 'assistant_files', ['uuid'], unique=False)
    op.create_table('assistants_to_files',
    sa.Column('assistant_files_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('voice_assistant_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assistant_files_uuid'], ['assistant_files.uuid'], name='assistants_to_files_assistant_files_uuid_fkey'),
    sa.ForeignKeyConstraint(['voice_assistant_uuid'], ['voice_assistant.uuid'], name='assistants_to_files_voice_assistant_uuid_fkey'),
    sa.PrimaryKeyConstraint('assistant_files_uuid', 'voice_assistant_uuid', name='assistants_to_files_pkey')
    )
    # ### end Alembic commands ###
