"""empty message

Revision ID: 1b5535499e67
Revises: 1746d7b5ae70
Create Date: 2024-09-12 14:40:25.781560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b5535499e67"
down_revision: Union[str, None] = "1746d7b5ae70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("account_balance_recharge_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("account_balance_recharge_to", sa.Float(), nullable=True)
    )
    op.drop_column("user", "account_balance_recharge")
    op.drop_column("user", "account_balance_min")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "account_balance_min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "account_balance_recharge",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "account_balance_recharge_to")
    op.drop_column("user", "account_balance_recharge_threshold")
    # ### end Alembic commands ###
