"""zilliz_doc_name

Revision ID: af4d1169ab04
Revises: 1b6cc0eb3848
Create Date: 2024-08-11 15:36:32.796157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af4d1169ab04"
down_revision: Union[str, None] = "1b6cc0eb3848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge", sa.Column("zilliz_doc_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "zilliz_doc_name")
    # ### end Alembic commands ###
