"""empty message

Revision ID: 520f0c826994
Revises: c00e3d88ee44
Create Date: 2024-03-23 12:10:07.873320

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "520f0c826994"
down_revision: Union[str, None] = "c00e3d88ee44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "conversation", ["id"])
    op.create_unique_constraint(None, "faqbot_conversation", ["id"])
    op.create_unique_constraint(None, "faqbot_message", ["id"])
    op.create_unique_constraint(None, "issue", ["id"])
    op.create_unique_constraint(None, "message", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "message", type_="unique")
    op.drop_constraint(None, "issue", type_="unique")
    op.drop_constraint(None, "faqbot_message", type_="unique")
    op.drop_constraint(None, "faqbot_conversation", type_="unique")
    op.drop_constraint(None, "conversation", type_="unique")
    # ### end Alembic commands ###
