"""empty message

Revision ID: 89e06527c9a0
Revises: 3ef6bc504b7c
Create Date: 2024-05-01 13:36:46.487174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89e06527c9a0"
down_revision: Union[str, None] = "3ef6bc504b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("clerk_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "clerk_id")
    # ### end Alembic commands ###
