"""empty message

Revision ID: bbfba5b01443
Revises: b95df7095f75
Create Date: 2024-09-11 20:36:31.411454

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bbfba5b01443"
down_revision: Union[str, None] = "b95df7095f75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_journal_entry", ["id"])
    op.drop_constraint(
        "user_journal_entry_userUuid_fkey", "user_journal_entry", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_journal_entry",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="NO ACTION",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_journal_entry", type_="foreignkey")
    op.create_foreign_key(
        "user_journal_entry_userUuid_fkey",
        "user_journal_entry",
        "user",
        ["userUuid"],
        ["uuid"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "user_journal_entry", type_="unique")
    # ### end Alembic commands ###
