"""empty message

Revision ID: 82afa1ddea66
Revises: 9ca6b8aa7c0e
Create Date: 2024-07-16 12:54:11.390877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82afa1ddea66'
down_revision: Union[str, None] = '9ca6b8aa7c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assistant_files', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistant_files', type_='unique')
    # ### end Alembic commands ###
