name: Trigger auto deployment for api-develop-syntag

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - 'apps/api/**'
    - '.github/workflows/api-AutoDeployTrigger-develop.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SYNTAG_SUBSCRIPTION_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/apps/api
          registryUrl: syntagregistryfastapi.azurecr.io
          registryUsername: ${{ secrets.SYNTAGREGISTRYFASTAPI_USERNAME }}
          registryPassword: ${{ secrets.SYNTAGREGISTRYFASTAPI_PASSWORD }}
          containerAppName: api-develop-syntag
          resourceGroup: syntag-resources
          imageToBuild: syntagregistryfastapi.azurecr.io/fast-api:${{ github.sha }}
          
            

