name: Trigger auto deployment for browser-automation

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'apps/browser/**'
    - '.github/workflows/browser-automation-AutoDeployTrigger-b5d5ffd3-9d53-4365-9401-dd88d807a8c5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SYNTAG_SUBSCRIPTION_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/apps/browser
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: syntagregistrybrowserautomation.azurecr.io
          registryUsername: ${{ secrets.BROWSERAUTOMATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BROWSERAUTOMATION_REGISTRY_PASSWORD }}
          containerAppName: browser-automation
          resourceGroup: syntag-resources
          imageToBuild: syntagregistrybrowserautomation.azurecr.io/browser-automation:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


